Feauture detalles sitio
Inwinkelried/ucse2024-IW-TP pull request #20
Opened 2024-10-19 21:04 UTC by renatowilliner

Se agrego boton de volver donde lo considere
Se quito la imagen harcodeade de los detalles
Se quito el valor True mostrado en la vista de detalles
Se quito descripcion y numero de pista del model
Se asigno un tamanio maximo a la imagen del complejo
Se agrego una notifiacion de confirmacion de las feautrue mas bonita
Se hizo que turnos en busca y por unirse sean una misma lista
Se dejo mas prolijo la vista de aceptar los turnos

2024-10-20 02:30 UTC, facundoschillino commented
Me parece que podriamos dejar los campos numero de pistas y descripcion y solamente sacarlo de la descripcion o detalle de los complejos. Tambien podriamos agregar  mas campos al form que usan los complejos para terminar el registro.
Lo otro todo de 10

2024-10-20 02:40 UTC, facundoschillino requested changes

2024-10-20 02:40 UTC, facundoschillino commented on padel/accounts/models.py
Aca le dejaria el campo y lo añadiria al form que tienen los complejos para terminar de completar los datos.

2024-10-20 02:40 UTC, facundoschillino commented on padel/templates/detalle_complejo.html
Acá dejaría el detalle completo del complejo cuando accedo a los detalles así tengo todo lo del complejo junto

2024-10-20 02:40 UTC, facundoschillino commented on padel/templates/mostrar_turnos_proximos.html
Willi no entendi lo que me pusiste en el excel sobre esto

2024-10-20 02:40 UTC, facundoschillino commented on padel/templates/visualizar_mis_complejos.html
Viendo esto me doy cuenta que tal vez sea buena decisión quitar la descripción de los complejos. Si dejaría el numero de pistas (Se me ocurre una feature para hacer con eso y los turnos)

2024-10-20 14:57 UTC, Inwinkelried requested changes
Revisar comentarios y corregir para poder mergear. Muy buenas las nuevas funcionalidades de notificaciones

2024-10-20 14:57 UTC, Inwinkelried commented on padel/accounts/models.py
estoy de acuerdo, es un dato útil

2024-10-20 14:57 UTC, Inwinkelried commented on padel/templates/detalle_complejo.html
Si, en el detalle es donde tengo que ver toda la informacion del complejo. Direccion y numero de pistas tienen que estar.

2024-10-20 14:57 UTC, Inwinkelried commented on padel/templates/registration/registro_complejos.html
> +          <label for="duracion turnos">duracion turnos (no anda):</label>
estas dos cositas tienen que volar a mi parecer

2024-10-20 14:57 UTC, Inwinkelried commented on padel/templates/visualizar_mis_complejos.html
Volemos la descripcion, fijarse de borrarla en todos lados menos en el model, por si queremos usarla para algo mas adelante

2024-10-20 17:23 UTC, renatowilliner commented on padel/accounts/models.py
Voy a dejar el campo 'cantidad_pistas' de nuevo

2024-10-20 17:29 UTC, renatowilliner commented on padel/templates/detalle_complejo.html
Deje en el detalle direccion y numero de pistas

2024-10-20 17:30 UTC, renatowilliner commented on padel/templates/mostrar_turnos_proximos.html
Que no pude fusionar las listas de turnos para reservar y tunos para unirse, son 2 listas distintas, primero se muestra una y dps la otra

2024-10-20 21:47 UTC, facundoschillino submitted a review, later dismissed

2024-10-20 22:06 UTC, Inwinkelried commented on padel/templates/detalle_complejo.html
>              <li class="list-group-item"> <strong>Numero de Pistas:</strong> {{ complejo.numero_de_pistas }}</li>
aca usas complejo.numero_de_pistas pero ese atributo no existe. (es cantidad_pistas)
Sin embargo, cantidad_pistas lo borraste de models, asi que no va a traer nada. 

Si queres mostrar el numero de pistas, vas a tener que volver a agregarlo en el modelo de complejo y hacer una nueva migracion

2024-10-21 21:55 UTC, Inwinkelried approved these changes

2024-10-21 21:55 UTC, merged