Notificaciones feauture
Inwinkelried/ucse2024-IW-TP pull request #21
Opened 2024-10-25 23:30 UTC by renatowilliner

Se han agregado las notificaciones de forma global
Se tuvo que modificar las redirecciones del metodo de registracion de complejo

2024-10-28 21:29 UTC, facundoschillino requested changes

2024-10-28 21:29 UTC, facundoschillino commented on padel/accounts/views.py
Aca nose maneja bien el flujo, cuando un usuario trata de registrar un compejo lo manda a home, pero deberia volver a cargarle el formulario

2024-10-28 21:29 UTC, facundoschillino commented on padel/static/padel/js/index.js
Quedaron unos comentarios sin borrar

2024-10-28 21:29 UTC, facundoschillino commented on padel/templates/base.html
Aca tambien quedaron unos comentarios sin borrar

2024-10-28 21:29 UTC, facundoschillino commented on padel/templates/home.html
Aca quedaron unos comentarios sin borrar

2024-10-28 21:43 UTC, Inwinkelried requested changes

2024-10-28 21:43 UTC, Inwinkelried commented on padel/accounts/views.py
> +            return redirect('home')
aca estas mandando a la home si el usuario ingresa datos invalidos, no va

2024-10-28 21:43 UTC, Inwinkelried commented on padel/templates/base.html
> +        <!-- Input oculto para pasar mensajes -->
borra estos comentarios croto

2024-10-28 22:51 UTC, renatowilliner commented on padel/templates/base.html
> +        <!-- Input oculto para pasar mensajes -->
Me encantan, es para guiarme

2024-10-29 00:18 UTC, Inwinkelried approved these changes

2024-10-29 00:19 UTC, merged